name: Deploy Storybook

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-latest
        permissions:
            contents: write
        concurrency:
            group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
            cancel-in-progress: true
        steps:
            - name: Checkout code
              uses: actions/checkout@v3
              with:
                  node-version: 20.13.1
                  cache: 'yarn'
                  cache-dependency-path: yarn.lock

            - name: Install dependencies
              run: yarn install --frozen-lockfile

            - name: Build Storybook
              run: yarn build-storybook

            - name: Deploy Storybook
              uses: peaceiris/actions-gh-pages@v3
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  publish_dir: storybook-static
